### ISSUE TITLE
Random dice (Backend)

### ISSUE THREAD

**Issue by Benjono** [Benjono/SoftwareEng#3]
Task card 2
Priority: 3
Value: 2
There needs to be a function that is used to generate two random numbers from 1 to 6.

**Comment by Jcorb08** [comment]
Use of `java.util.Random` library, to generate two random numbers with the bound of 6 and add these together. Something like this but with a return statement:

`import java.util.Random;`
`Random rand = new Random();`
`int roll1 = rand.nextInt(6) + 1;`
`int roll2 = rand.nextInt(6) + 1;`
`return (roll1, roll2)`

This returns a tuple in order to show the two rolls.

Source:
https://stackoverflow.com/questions/5887709/getting-random-numbers-in-java
